// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3HoT7sT7egLQfVMXC2AD_EWv9IW65RpI',
    appId: '1:774532581553:web:c894b72a8662e78a217a90',
    messagingSenderId: '774532581553',
    projectId: 'pet-adoption-app-9a14a',
    authDomain: 'pet-adoption-app-9a14a.firebaseapp.com',
    storageBucket: 'pet-adoption-app-9a14a.appspot.com',
    measurementId: 'G-016R5H8DJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlIXgQDwRU6v37Ro6685NQ6BqP7l6lg3c',
    appId: '1:774532581553:android:ced0200ea0b21ae7217a90',
    messagingSenderId: '774532581553',
    projectId: 'pet-adoption-app-9a14a',
    storageBucket: 'pet-adoption-app-9a14a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdgIg5JDL1S8c4sY9N4_7HGNz2_cF-Zbg',
    appId: '1:774532581553:ios:ba7988404fa18fe6217a90',
    messagingSenderId: '774532581553',
    projectId: 'pet-adoption-app-9a14a',
    storageBucket: 'pet-adoption-app-9a14a.appspot.com',
    iosClientId:
        '774532581553-qvdj8jstm0kvqi7j4rq704p43aji5qqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.adoptPets',
  );
}
